eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9001/service-discovery/eureka/

server:
  port: 9002
  servlet:
      context-path: /auth

spring:
  application:
    name: authorization