eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9001/service-discovery/eureka/

server:
  port: 9020
  servlet:
    context-path: /blog

spring:
  application:
    name: frontend

zuul:
  routes:
    api:
      path: /api/**
      serviceId: api
      stripPrefix: false