matrix:
  include:
    - language: java
      jdk: oraclejdk9

    - language: node_js
      node_js:
          - node
      before_script:
          - yarn global add @angular/cli
      script:
          - ng build --prod
      cache:
        yarn: true
        directories:
            - node_modules

notifications:
  email: false