eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9001/service-discovery/eureka/

security.oauth2.resource.jwt.key-value: awesome-key

server:
  port: 9010

spring:
  application:
    name: api