server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: api

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9002/service-discovery/eureka/