server.port: 80

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

  profiles:
    active: native # need this to use classpath config location instead of Git repository

  security:
    user:
      password: 123