logging.config: classpath:log4j2-docker.xml

server.port: 80

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

  profiles:
    active: native # need this to use classpath config location instead of Git repository

  security:
    user:
      password: 123

---
spring:
  profiles: local

logging.config: classpath:log4j2-local.xml

server.port: 9000
