eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery/eureka/

jwt:
  header: Authorization
  param: token
  secret: awesome
  expiration: 604800000
  prefix: bearer
  route:
    authentication:
      path: auth
      token: token
      refresh: refresh

server.port: 80
