eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9001/discovery/eureka/

jwt:
  header: Authorization
  param: token
  secret: awesome
  expiration: 604800000
  prefix: bearer
  route:
    authentication:
      path: auth
      token: token
      refresh: refresh

server:
  port: 9002
  servlet:
    context-path: /auth

spring:
  application:
    name: service-discovery
  cloud:
    config:
      uri: http://localhost:9000/config
      fail-fast: true
      password: 123
      username: user
