eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery/eureka/

server.port: 80

zuul:
  routes:
    api:
      path: /api/**
      serviceId: api
      stripPrefix: false